export const COFOUNDER_SKILLS = [
  "Full-Stack Development",
  "Frontend (React/Next.js)",
  "Backend (Node.js/Python)",
  "Mobile Development",
  "AI/ML Engineering",
  "Data Science",
  "IoT & Hardware",
  "Drone Technology",
  "Blockchain",
  "Cloud & DevOps",
  "Product Management",
  "UI/UX Design",
  "Business Development",
  "Sales & Marketing",
  "Finance & Accounting",
  "Operations & Supply Chain",
  "Agricultural Science",
  "Agronomy",
  "Soil Science",
  "Plant Biology",
  "Animal Husbandry",
  "Food Technology",
  "Rural Distribution",
  "Government Relations",
  "Fundraising",
  "Legal & Compliance",
] as const

export type CoFounderSkill = (typeof COFOUNDER_SKILLS)[number]
